### ISSUE TITLE
Planning meetings

### ISSUE THREAD

**Issue by cfarm** [cfpb/hackathon#1]
## Planning meeting 1

Let's meet and talk about planning a hack day for government designers and developers at the January regroup! Take some time beforehand to skim the following excellent resource on planning a hackathon-type event: https://hackathon.guide/

Things to decide:

Logistics:
- Who is invited? Other federal agencies/federal employees.
- Where can we host it? Possible locations for Tuesday/Wed/Thurs. We can't do CFPB because we don't have open Wifi.
  - Government Innovation Lab (Brad has a contact).
  - U.S.D.S. / 18F. Erie has offered space to us before.
- Food: Bill or Front Office Pizza

Format:
- Non competitive
- Recognize different types of projects after demos with CANDY
- Project teams: propose them + sign up in advance, to promote event + teams.
  - Setup night before the big day
  - Will is on it
- Structure
  - Workshops in one room, hacking in another.
  - Teams can form in advance OR at the event.
  - Teams will propose/present their ideas at the start of the day
  - Teams can demo their work at the end
  - Party time after
- Workshops: Chris will organize.
  - Chuck - Agile Training
  - Lightning Workshops from regroup
  - Figure out where to run them - needs to be same location/day as the hackathon. Maybe just morning workshops.
- Code of Conduct: Cat will find one to reuse - maybe we can reuse Nodeschool CoC or the open source policy https://github.com/cfpb/project-open-source/issues/8

Planning: 
- Next steps: Everyone has 1 responsibility every 2 weeks.

Questions for future planning

Theme????????
- CCDB Data
- HMDA Data
- 

Outreach
- Bill will reach out to other agencies/contacts
- Adam will reach 18F. Can they organize their regroup at the same time as ours to attend this meetup?
- National Cancer Research Institute - Will
- Geospatial intelligence agency
- US PTO 

Names
- add your ideas to name the hackathon in another thread

Website in this here repo
- Chris will make it pretty

**Comment by bradhicks** [comment]
Emails have been sent to Erie (18F) and Arianne (Lab @ OPM) for space.

**Comment by cfarm** [comment]
### Todos
- [ ] @virtix outreach to other agencies

## 
- [ ] @ascott1 outreach
- [ ] @ascott1 confirm more workshops in addition to Chuck's

## 
- [ ] @contolini basic website on github.io where we can add event details as we confirm

## 
- [ ] @bradhicks confirm event space + date
- [ ] @bradhicks confirm food budget

## 
- [ ] @willbarton create sign-ups / project proposals function on Github
- [ ] @willbarton design structure/schedule for team formation
- [ ] @willbarton + @marcesher  plan team/project setup night the day before event

## 
- [ ] @cfarm solicit name ideas
- [x] @cfarm post code of conduct for team review
- [ ] @cfarm outreach

### Backlog
- [ ] Setup night venue/logistics - keep it simple
- [x] how will participants sign up to attend?
- [ ] create schedule for event day
- [ ] order pizza
- [x] Brainstorm CFPB folks to invite
- [ ] ....

**Comment by cfarm** [comment]
Another resource for planning events like this http://opensource-events.com/

**Comment by bradhicks** [comment]
@jonathanrubin Do you have any other free government space ideas for the planned hackathon? I'm still waiting to hear back from Gray Brooks at 18F. OPM is getting back to me about their fee after requesting more info on the event.

**Comment by jdrubin** [comment]
Brad,
I'll check in with Gray Brooks. There are lots of other partners at GSA besides 18F that we can talk to. How many people are we talking about? And for how many hours?

**Comment by jonathanrubin** [comment]
Am I supposed to be apart of this thread ??

**Comment by bradhicks** [comment]
@jdrubin Oh, look, the right Jon Rubin joined us!  lol  Headcount is TBD and I've been estimating a full work day for the number of hours, but I don't know if that's standard.  I haven't read any of the materials that Cat has helpfully provided us links to.

**Comment by cfarm** [comment]
8 hour workday for this event is correct.

Headcount really depends on our space - @bradhicks any estimates based on the places we've been in touch with?

**Comment by bradhicks** [comment]
Hi all, no word yet on a cost estimate from OPM nor a responsive contact from 18F, although Jon is now helping us with multiple GSA contacts. We should have more news soon, but possibly not by 3PM today. 

For food, leadership normally pays out of pocket to provide it for team members at events since we can't use our budget. Since this will be attended by folks outside the CFPB, is there any reason why we can't ask for $5 from participants and offer to coordinate the ordering and delivery? Leadership could make up any difference between the amount collected and the total cost.

**Comment by jonathanrubin** [comment]
For hackers you guys need some work. I'm not the Jon Rubin you're trying to
reach.

**Comment by Scotchester** [comment]
@jonathanrubin We apologize for tagging you incorrectly earlier on in the thread. If you'd like to stop receiving emails for this issue, you can visit the issue page on GitHub and click the **Unsubscribe** button on the right sidebar.

**Comment by cfarm** [comment]
# Planning Meeting 2
- Follow up on above todos
- Choose a theme

Next Steps
- [x] Survey for CFPBers about the theme: would you show up to a hackthon with this format ___: @contolini 
- [ ] Confirm date and add to Outlook calendar for regroup
- [ ] Once we have confirmed date + space we will open sign-ups
- [ ] Sign-up form - use Google Form, include workshops @cfarm

**Comment by cfarm** [comment]
@contolini this was the site where we signed up for the Federal Open Source Policy Town Hall: https://login.max.gov

**Comment by jdrubin** [comment]
All,
Finally heard back from GSA. Do we have a target date and an expected # of people? They say we'd need to party with either 18F or DigitalGov University to hold it there - they have a new policy of NO outside agencies for events :(

**Comment by bradhicks** [comment]
Thanks @jdrubin ! We are targeting the week of regroup (Tues, Wed, or Thurs). For number of people, we are estimating 30. I don't think partnering is impossible. How do they define that?

**Comment by jdrubin** [comment]
Excellent. Let me check!

**Comment by cfarm** [comment]
# Planning Meeting 3

## Theme!!!
- GovCode issues 
  - GovBugs???? need a name
  - Learn to code and make your first contribution 
  - Bugs
  - New features - eRegs theming, immersion-style small projects, CapitalJS
  - Design: PDF -> webpage
  - Suggest your ideas and give a place to solicit teammates

## Location!!!!!!!

TBD

## Date

Wednesday, January 27

## Signup Form
- [ ] @willbarton will send @farmanc whatever she needs to collect in the signup form about Projects/teams/help wanted tagging info

## Outreach
- [ ] @farmanc will invite CFPBers
- [ ] @ascott1 and @marcesher will invite external folks
  - github gov group

## Website
- [ ] @farmanc we need someone to work on the website!!!!!! 
  - links: signup form, code of conduct, projects
  - name, date, location
  - who is invited
  - need design help!!!!!!

**Comment by jdrubin** [comment]
Update on space! GSA and their DigitalGov University program say that if the hackathon is for the whole federal community, they have the following space availability in a room that holds 40:

Friday, Jan. 22
Wed, Feb. 3
Thurs, Feb 4

I have these reserved from 9am-5pm each of those days.

They usually prefer to create registration pages for events in their building, which they can also help market for us. Let me know if any of these work.

**Comment by bradhicks** [comment]
@jdrubin That looks great except for the dates that fall outside regroup week so I'm not sure that they'll work. Thanks for getting us other options, though. This is harder than I thought.

@cfarm I spoke to Ashley Wood at the Lab at OPM today. She reserved the lab for all day on Wednesday, 1/27 for us, but I'm afraid it isn't ideal space for our event. There is only one large, open space available so running the hackathon and workshops at the same time in the same room will be tough. However, if we don't find more suitable space the week of regroup, here's some additional info:
- The space fits 35 people (there is a couch to one corner but no separate lounge space) 
- There is WiFi, a projector and screens at both ends, a polycom, and a microphone
- There is no cell phone service
- Unfortunately, the two adjacent conference rooms are reserved for the USAJobs war rooms for several months and are not reservable by us
- They are building another conference room but it won't be ready by 1/27
- The cost for a full day will be between $500-1,000 and I haven't had it approved yet

I can arrange to do a tour in advance if that's necessary, but I'm guessing other D+D folks have been there before and can tell us what they think of it.

**Comment by jdrubin** [comment]
I would not recommend the OPM room for something like this, although the people are fabulous. The lack of cell service is an issue, it's very loud and it's hard to unify the space because of the layout, columns, and some other reasons. Hmmm....

**Comment by bradhicks** [comment]
Good to know. Back to the drawing board! :)

**Comment by cfarm** [comment]
# Planning Meeting 4

We don't have space for an event to host other federal employees, so we decided to keep this CFPB-only for the January regroup event. We will have it on Wednesday 1/27 and we ask @bradhicks to help us find space in Noma office - I will reach out on Monday.
- @ascott1 reach out to 18F for projects/issues/features for the event to post with Help Wanted tags for Govcode.
- We need an update from @willbarton about projects/signups - I will reach out
- @contolini will confirm workshops
- Working name: CFPB Hack Day

**Comment by bradhicks** [comment]
Sherri reserved Room 801 at NoMa on 1/27 from 8:30-5:30 for the CFPB Hack Day.

**Comment by willbarton** [comment]
@cfarm Sorry I missed the meeting today. 

Basic idea:
- Form to submit project ideas creates an open issue in this repo with the label "Hackathon Project".
- Separate form to read list of submitted projects and allow people to volunteer. Volunteering comments on the issue.

This gives us project-related issues that can be used for more than sign-ups, and keeps things in GitHub issues. It also requires a GitHub account and to be logged in (anonymous volunteerings don't help us).

Anyone have any strong feelings on this? I've started working on proof-of-concept JavaScript to use the GitHub API to do this. I'll just need some help, probably next week, making it nice and pretty for the hackathon page.

**Comment by cfarm** [comment]
@bradhicks Do you think we could book one of the 2nd floor auditorium rooms? We also thought of booking a floor of smaller conference rooms for teams who want their own space to work in throughout the day.

**Comment by cfarm** [comment]
@willbarton what if rather than a form, we have some links/buttons that do the same functionality - eg create a new github issue with the proper label, or post a comment to an existing issue to join a team/project.

like this:
https://github.com/cfpb/hackathon/issues/new?labels=bug

**Comment by willbarton** [comment]
@cfarm That certainly works, and is far lower-effort.

I just like the idea of project proposals being GitHub issues that can then have sign-ups and project-related discussion in one place.

**Comment by willbarton** [comment]
I do think it would still be a good idea to use the GitHub API to read a list of proposed projects for the web page we'll have set up. We can link from there to the comment box for volunteering.

**Comment by willbarton** [comment]
I have a conceptual proof of how it might work: 

http://willbarton.github.io/hackathon/

**Comment by bradhicks** [comment]
@cfarm Both sides of the auditorium are booked for regroup the entire week. I haven't seen a schedule, but I'm assuming that there will be a need for someone to use the whole space that day for something. Sherri moved the Hackathon to 701 A and B so that there is plenty of space. Does that work?

**Comment by cfarm** [comment]
Sounds good. Thanks @bradhicks!

**Comment by willbarton** [comment]
@mebates asks a good question: Do we know that D&D/T&I aren't going to be scheduling anything else for this day?

**Comment by cfarm** [comment]
@willbarton Yes, this is something that @virtix confirmed to be the case.

**Comment by cfarm** [comment]
# Planning Meeting 5 agenda
- @willbarton sign up form / process updates
- @bradhicks space updates

## next steps!
- @contolini will join forces with @designlanguage to do lightning workshops during hackathon on 1/27
  - they need to book a separate room for the workshops on the same day.
- @bradhicks will double check the auditorium and regroup schedule availability for hackathon, if we can use auditorium, then we'll have 701A+B for the workshops booked already.
- @willbarton write a T&I /D&D Newsletter blurb to invite people to sign up for projects and workshops ahead of time. otherwise promotion will happen through Regroup schedule announcements
- @cfarm will assist @willbarton on website + posting project/workshop threads

**Comment by cfarm** [comment]
Website for adding project/workshop ideas and signing up for each:

http://cfpb.github.io/hackathon/

CHECK IT OUT

**Comment by willbarton** [comment]
@marteki points out that we need to explicitly reach out to UX, design, and further afield to get some more project suggestions that aren't necessarily dev-centric, and to increase awareness that this is happening and that non-devs are welcome.

**Comment by mistergone** [comment]
I've obviously been on leave for a bit here, but it seems like the Agile/Scrum workshop might be "out of scope" for what we're doing now. If we want to squeeze it in, I'm still very happy to do it, but I can also put it on hold and do it at a future hackathon. :smile:

**Comment by cfarm** [comment]
# Planning Meeting 6

## Demos

~~~ CaTEgoriEs ~~~
- peoples' choice
- design
- most test coverage
- bestest readme
- best documentation
- #1 masochist award
- most altruistic

## Next steps
- [x] @willbarton will update the website with a GovCode link or project
- [x] @marcesher will reach out to design inbox to get photogs at event
- [x] @cfarm will email a blurb to share with non-T&I folks to invite them, and ask T&I folks to invite with their colleagues outside T&I
- [x] @cfarm will send note for newsletter + intranet
- [x] @contolini will recruit design projects
- [x] @contolini @bradhicks et al will email non-T&I folks they work with to invite them
- [ ] @cfarm feedback form for during/after event

**Comment by cfarm** [comment]
# Post-hack-day tasks
- [ ] Feedback form sharing and collecting
- [ ] Blog post on cfpb.github.io (and cf.gov?)
- [ ] after action review type meeting to capture what to do better next time

**Comment by cfarm** [comment]
Join your colleagues at <a href="http://cfpb.github.io/hackathon/">CFPB Hack Day</a>, a day-long event on Wednesday, January 27 in Conference Room 701 at the Noma office. We'll get started at 9am when we'll form teams and spend a few hours putting our heads together to make something new or help make existing tools + resources better. 

This event is taking place during the  Technology & Innovation January regroup, and all CFPB employees and contractors are invited to attend. We are expecting everyone from designers and developers to subject matter experts to attend this event.

Some of the projects CFPB'ers have proposed so far include: creating financial education games, a <a href="https://github.com/cfpb/hackathon/issues/25">CFPB meme generator</a>, <a href="https://github.com/cfpb/hackathon/issues/24">a mobile app version of the Owning a Home Explore interest rates tool</a>, writing new math and code for a <a href="https://github.com/cfpb/hackathon/issues/19">financial formula JavaScript library</a>, and <a href="https://github.com/cfpb/hackathon/issues/28">improving 18F's U.S. Web Design Standards</a>. 

Visit the CFPB Hack Day website to propose a project of your own, recruit team members, join an existing project team, and learn more: http://cfpb.github.io/hackathon/

And please feel free to reach out to Catherine.Farman@cfpb.gov with any questions or feedback!

**Comment by cfarm** [comment]
# Meeting 7
- investigate after action review person

**Comment by cfarm** [comment]
# Meeting 8

### Day before tasks
- Setup room
- Power strips in the room @bradhicks request power strips from Service Desk
- Print handouts with logistics (see https://hackathon.guide/) @cfarm
  - hack day chat in mattermost
  - breakout rooms
- do we need nametags + sharpies? any other supplies? @bradhicks will get from Kimberley
- @bradhicks  pick up paper plates + napkins for the 'za :pizza: 
- @willbarton reach out to project leaders to remind them how to pitch.
- @contolini wrap surprise prizes
- [ ] get dongle(s)

### Day of tasks
- @bradhicks bring sailing hats
- brad candy

**Comment by cfarm** [comment]
@marcesher Now that we have a new date scheduled (April 14), can you reach out to the photography team again to see their availability? If they are not free then we need to re-confirm that Daniel P and Jenn H can tag-team still.

**Comment by cfarm** [comment]
@marcesher also volunteered to head up the coffee / morning snack procurement

**Comment by cfarm** [comment]
## 1 week before tasks
- [ ] reminder emails
- [ ] reminder announcement on intranet
- [ ] ask folks to bring project ideas/setup tasks to dev cop on april 12th
- [ ] @contolini pizza prep - how much $$$ and remind funders

**Comment by cfarm** [comment]
## Monday tasks
- [ ] @ascott1 event flyers hang em in bathrooms
